import { SimpleWordType } from '@/types/word'

export const words: SimpleWordType[] = [
  {
    id: 0,
    name: 'CI',
    meaning:
      '기업의 이미지를 나타내는 로고나 디자인을 말해요.기업의 이미지를 나타내는 로고나 디자인을 말해요.기업의 이미지를 나타내는 로고나 디자인을 말해요기업의 이미지를 나타내는 로고나 디자인을 말해요',
    category: '디자인',
    viewCount: 83,
    commentCount: 9,
  },

  {
    id: 1,
    name: 'ROI(Return On Investment)',
    meaning:
      '투자한 자본 대비 수익을 얼마나 얻었는지 측정하는 지표예요 (이익 ÷ 투자액 × 100)',
    category: '비즈니스',
    viewCount: 150,
    commentCount: 20,
  },
  {
    id: 2,
    name: 'B2B(Business-to-Business)',
    meaning: '기업 간 제품이나 서비스를 거래하는 비즈니스 모델이에요',
    category: '비즈니스',
    viewCount: 85,
    commentCount: 10,
  },
  {
    id: 3,
    name: 'API',
    meaning: '응용 프로그램 간에 상호작용을 가능하게 하는 인터페이스예요',
    category: '개발',
    viewCount: 102,
    commentCount: 18,
  },
  {
    id: 4,
    name: 'UX 디자인',
    meaning: '사용자 경험을 고려하여 제품이나 서비스를 설계하는 과정이에요',
    category: '디자인',
    viewCount: 145,
    commentCount: 22,
  },
  {
    id: 5,
    name: 'P2P(Peer-to-Peer)',
    meaning: '개인 간에 직접적으로 상품이나 서비스를 거래하는 시스템이에요',
    category: '비즈니스',
    viewCount: 75,
    commentCount: 8,
  },
  {
    id: 6,
    name: 'Git',
    meaning: '분산형 버전 관리 시스템으로, 소스 코드를 관리하는 데 사용돼요',
    category: '개발',
    viewCount: 98,
    commentCount: 15,
  },
  {
    id: 7,
    name: '각출',
    meaning: '각자의 비용을 각자 지불하는 것을 의미해요',
    category: '비즈니스',
    viewCount: 13,
    commentCount: 5,
  },
  {
    id: 8,
    name: 'CRM',
    meaning: '고객과의 관계를 관리하여 매출을 극대화하는 전략이에요',
    category: '비즈니스',
    viewCount: 95,
    commentCount: 12,
  },
  {
    id: 9,
    name: 'ERP',
    meaning: '기업의 자원을 통합적으로 관리하기 위한 소프트웨어 시스템이에요',
    category: '비즈니스',
    viewCount: 110,
    commentCount: 18,
  },
  {
    id: 10,
    name: 'SWOT 분석',
    meaning: '강점, 약점, 기회, 위협을 분석하여 전략을 수립하는 도구예요',
    category: '비즈니스',
    viewCount: 130,
    commentCount: 22,
  },
  {
    id: 11,
    name: 'REST API',
    meaning: 'HTTP를 통해 통신하는 웹 서비스를 구축하기 위한 인터페이스예요',
    category: '개발',
    viewCount: 112,
    commentCount: 17,
  },
  {
    id: 12,
    name: 'UI 디자인',
    meaning: '사용자 인터페이스를 설계하여 사용자 경험을 개선하는 작업이에요',
    category: '디자인',
    viewCount: 150,
    commentCount: 25,
  },
  {
    id: 13,
    name: 'HTML',
    meaning: '웹 페이지의 구조를 정의하는 마크업 언어예요',
    category: '개발',
    viewCount: 90,
    commentCount: 10,
  },
  {
    id: 14,
    name: '브랜딩',
    meaning:
      '제품이나 서비스를 차별화하여 고유의 이미지로 자리잡게 하는 과정이에요',
    category: '비즈니스',
    viewCount: 135,
    commentCount: 20,
  },
  {
    id: 15,
    name: '스크럼',
    meaning: '소프트웨어 개발에서 팀이 협력하여 작업을 수행하는 방법론이에요',
    category: '개발',
    viewCount: 125,
    commentCount: 16,
  },
  {
    id: 16,
    name: '프로토타이핑',
    meaning: '제품이나 서비스의 초기 모델을 제작하여 테스트하는 과정이에요',
    category: '디자인',
    viewCount: 142,
    commentCount: 19,
  },
  {
    id: 17,
    name: '클라우드 컴퓨팅',
    meaning:
      '인터넷을 통해 데이터와 프로그램을 저장하고 접근할 수 있는 기술이에요',
    category: '개발',
    viewCount: 138,
    commentCount: 23,
  },
  {
    id: 18,
    name: '로고 디자인',
    meaning: '브랜드나 기업을 상징하는 이미지를 만드는 작업이에요',
    category: '디자인',
    viewCount: 92,
    commentCount: 11,
  },
  {
    id: 19,
    name: '마케팅 전략',
    meaning: '제품이나 서비스를 효과적으로 판매하기 위한 계획과 방법을 말해요',
    category: '비즈니스',
    viewCount: 167,
    commentCount: 30,
  },
  {
    id: 20,
    name: 'DevOps',
    meaning: '소프트웨어 개발과 운영을 통합하여 효율성을 높이는 방법이에요',
    category: '개발',
    viewCount: 144,
    commentCount: 21,
  },
  {
    id: 21,
    name: '브랜드 아이덴티티',
    meaning: '브랜드가 지닌 고유한 이미지와 가치를 나타내는 요소를 말해요',
    category: '디자인',
    viewCount: 136,
    commentCount: 18,
  },
  {
    id: 22,
    name: 'SEO',
    meaning:
      '검색 엔진에서 웹사이트의 노출을 증가시키기 위한 최적화 작업이에요',
    category: '비즈니스',
    viewCount: 154,
    commentCount: 24,
  },
  {
    id: 23,
    name: '테스트 주도 개발',
    meaning: '테스트 케이스를 먼저 작성하고 소프트웨어를 개발하는 방법론이에요',
    category: '개발',
    viewCount: 118,
    commentCount: 15,
  },
  {
    id: 24,
    name: '모바일 퍼스트 디자인',
    meaning: '모바일 기기에서의 사용성을 우선으로 고려하여 설계하는 방법이에요',
    category: '디자인',
    viewCount: 123,
    commentCount: 20,
  },
  {
    id: 25,
    name: '고객 세분화',
    meaning:
      '고객을 다양한 기준에 따라 세분화하여 마케팅 전략을 수립하는 과정이에요',
    category: '비즈니스',
    viewCount: 121,
    commentCount: 13,
  },
  {
    id: 26,
    name: '애자일',
    meaning:
      '유연한 대응과 반복적 개선을 강조하는 소프트웨어 개발 방법론이에요',
    category: '개발',
    viewCount: 110,
    commentCount: 18,
  },
  {
    id: 27,
    name: '리스크 관리',
    meaning: '기업이 직면할 수 있는 위험을 식별하고 대응하는 과정이에요',
    category: '비즈니스',
    viewCount: 98,
    commentCount: 12,
  },
  {
    id: 28,
    name: '트렌드 분석',
    meaning: '시장의 변화를 분석하고 미래의 흐름을 예측하는 과정이에요',
    category: '비즈니스',
    viewCount: 145,
    commentCount: 20,
  },
  {
    id: 29,
    name: '그로스 해킹',
    meaning: '성장을 촉진하기 위한 창의적이고 분석적인 마케팅 기법이에요',
    category: '비즈니스',
    viewCount: 158,
    commentCount: 27,
  },
  {
    id: 30,
    name: '백엔드 개발',
    meaning: '서버와 데이터베이스를 관리하고 처리하는 개발 영역이에요',
    category: '개발',
    viewCount: 120,
    commentCount: 14,
  },
  {
    id: 31,
    name: '비주얼 아이덴티티',
    meaning: '브랜드의 시각적 요소들을 통해 전달하는 이미지예요',
    category: '디자인',
    viewCount: 110,
    commentCount: 15,
  },
  {
    id: 32,
    name: '핀테크',
    meaning: '금융과 기술을 결합해 혁신적인 금융 서비스를 제공하는 산업이에요',
    category: '비즈니스',
    viewCount: 132,
    commentCount: 19,
  },
  {
    id: 33,
    name: '데이터 마이닝',
    meaning: '대량의 데이터를 분석해 유용한 정보를 추출하는 과정이에요',
    category: '개발',
    viewCount: 140,
    commentCount: 18,
  },
  {
    id: 34,
    name: '와이어프레임',
    meaning: '웹사이트나 앱의 기본 구조를 시각적으로 표현한 설계도예요',
    category: '디자인',
    viewCount: 122,
    commentCount: 16,
  },
  {
    id: 35,
    name: '비즈니스 모델',
    meaning: '기업이 가치를 창출하고 수익을 창출하는 방법과 구조예요',
    category: '비즈니스',
    viewCount: 165,
    commentCount: 22,
  },
  {
    id: 36,
    name: '프론트엔드 개발',
    meaning: '사용자가 직접 상호작용하는 웹사이트의 부분을 개발하는 영역이에요',
    category: '개발',
    viewCount: 138,
    commentCount: 20,
  },
  {
    id: 37,
    name: '프로덕트 디자인',
    meaning:
      '사용자의 요구와 시장의 필요를 반영하여 제품을 설계하는 작업이에요',
    category: '디자인',
    viewCount: 128,
    commentCount: 17,
  },
  {
    id: 38,
    name: '서스테이너빌리티',
    meaning: '기업 활동이 환경과 사회에 미치는 영향을 최소화하는 전략이에요',
    category: '비즈니스',
    viewCount: 150,
    commentCount: 25,
  },
  {
    id: 39,
    name: '머신 러닝',
    meaning: '컴퓨터가 데이터를 학습하여 스스로 성능을 향상시키는 기술이에요',
    category: '개발',
    viewCount: 142,
    commentCount: 21,
  },
  {
    id: 40,
    name: '컬러 팔레트',
    meaning: '브랜드나 디자인 프로젝트에 사용되는 색상의 조합을 말해요',
    category: '디자인',
    viewCount: 115,
    commentCount: 12,
  },
  {
    id: 41,
    name: '벤치마킹',
    meaning:
      '타사의 우수한 사례를 참고하여 자사의 성과를 향상시키는 기법이에요',
    category: '비즈니스',
    viewCount: 136,
    commentCount: 16,
  },
  {
    id: 42,
    name: '풀스택 개발',
    meaning: '프론트엔드와 백엔드를 모두 다룰 수 있는 개발자를 의미해요',
    category: '개발',
    viewCount: 148,
    commentCount: 23,
  },
  {
    id: 43,
    name: '타이포그래피',
    meaning: '문자의 배열과 디자인을 통해 시각적 효과를 극대화하는 기술이에요',
    category: '디자인',
    viewCount: 124,
    commentCount: 14,
  },
  {
    id: 44,
    name: '이커머스',
    meaning:
      '온라인 플랫폼을 통해 상품과 서비스를 거래하는 전자 상거래를 의미해요',
    category: '비즈니스',
    viewCount: 167,
    commentCount: 28,
  },
  {
    id: 45,
    name: '버전 관리',
    meaning: '소스 코드의 변경 이력을 관리하고 추적하는 시스템이에요',
    category: '개발',
    viewCount: 110,
    commentCount: 12,
  },
  {
    id: 46,
    name: '인포그래픽',
    meaning:
      '정보를 시각적으로 표현하여 이해하기 쉽게 전달하는 디자인 방식이에요',
    category: '디자인',
    viewCount: 152,
    commentCount: 19,
  },
  {
    id: 47,
    name: '고객 관계 관리',
    meaning: '고객과의 장기적인 관계를 구축하고 유지하는 비즈니스 전략이에요',
    category: '비즈니스',
    viewCount: 139,
    commentCount: 24,
  },
  {
    id: 48,
    name: '클린 코드',
    meaning: '가독성과 유지보수성이 높은 코드를 작성하는 개발 원칙이에요',
    category: '개발',
    viewCount: 119,
    commentCount: 15,
  },
  {
    id: 49,
    name: '디자인 시스템',
    meaning:
      '일관된 사용자 경험을 위해 디자인 규칙과 패턴을 체계화한 시스템이에요',
    category: '디자인',
    viewCount: 145,
    commentCount: 21,
  },
  {
    id: 50,
    name: '네트워킹',
    meaning: '사업적 또는 개인적 관계를 구축하고 유지하는 활동을 의미해요',
    category: '비즈니스',
    viewCount: 132,
    commentCount: 18,
  },
]
